### PR TITLE
Improved screenshot module

### PR DESCRIPTION
**Pull request by retro-engineer**
The screenshot module no longer touches disk

### CODE REVIEW

**Comment by xorrior** [comment]
@peto01  This is dope man. I'll see if @rvrsh3ll can test this out so we can merge it. Thanks alot man!

**Comment by xorrior** [comment]
@peto01 Can you submit this to the Empire 2.0 repo?? This is really dope man. Thanks for the help!

**Comment by retro-engineer** [comment]
Hi Chris,

Glad I could help. I’m not used to collaborating on GitHub, so please tell me if you need any action on my part.

Also, I love EmPyre on OSX, so if you have any needs for assistance, I would gladly help out.

BR

--

Peter Toth
EPM Professional Ambassador

Sucaba Technologies AB
P.O Box 7735
SE-10395 Stockholm
Sweden

Mobile: +46 708 997 333

On 22 Aug 2017, at 05:27, Chris Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


@peto01<https://github.com/peto01> This is dope man. I'll see if @rvrsh3ll<https://github.com/rvrsh3ll> can test this out so we can merge it. Thanks alot man!

**Comment by xorrior** [comment]
@peto01 you can resubmit the module here: https://github.com/EmpireProject/Empire . If you need any help porting it over, just let me know. It shouldn't be too difficult.

**Comment by retro-engineer** [comment]
Which branch would you like me to use? Dev i guess?

--

Peter Toth
EPM Professional Ambassador

Sucaba Technologies AB
P.O Box 7735
SE-10395 Stockholm
Sweden

Mobile: +46 708 997 333

On 22 Aug 2017, at 14:48, Chris Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


@peto01<https://github.com/peto01> you can resubmit the module here: https://github.com/EmpireProject/Empire . If you need any help porting it over, just let me know. It shouldn't be too difficult.

**Pull request closed without merging**
