### PR TITLE
Allow the possibility to separate between socket address and listener's public IP address

### PR DESCRIPTION
**Pull request by imaibou**
Sometimes, we need to listen on the public server and redirect the traffic into our empire listener on the internal server using DNAT, we would like to set the listeners "Host" to the public IP address while listening on the internal server. This way, all the stager payloads would contain the public IP address while the EmPyre instance turns on the local machine. This pull request would allow us to implement this scenario.
On the empire powershell project, the listener listens by default to the 0.0.0.0 IP address (https://github.com/PowerShellEmpire/Empire/blob/e43fb9463410dfa804e0aa507a5842c1a0504c0d/lib/common/http.py#L150).

### CODE REVIEW

**Comment by killswitch-GUI** [comment]
I have talked with @rvrsh3ll about this pull request about a week ago and how we would like to handle this. My major concern with this method is if a user accidentally binds to a bad IP on a public box with multiple IP's (I have this on my VPS) than they could incidentally open EmPyre up to all inferaces that where not intended. @HarmJ0y Is the primary on Empire, so he may ok with this since its just aligning the two. Maybe a warning statement?  I could also be over thinking it.

**Comment by imaibou** [comment]
In case a user accidentally binds to a bad IP, he gets the "[!] Error starting listener on IP address "+lhost+", trying 0.0.0.0 ..." error message, and would (hopefully) recognize his mistake. In the 3 seconds between the creation of the listener on all the interfaces, and the realization of his mistake and executing kill [listener], I can't imagine anything bad that could happen. And even if the listener's port is already in use in one of the interfaces, EmPyre can't listen in that port, so no damage will be done.

Another approach to resolving this issue is to separate between the two addresses in the listeners configuration, so that when a user creates a listener, it would ask for:
- IP address/ port number where the socket would bind
- IP address/ port number that would be referenced in the stager
This would allow for a clean separation and leave the care of creating DNAT rules for the user in case he wants to separate the two.
This second solution would however require some changes in the conception level of EmPyre and may take some time. If you agree on the second solution, I would be happy to propose another pull request.

**Comment by rvrsh3ll** [comment]
Hello,

I'd like to merge this fix but, it failed for me upon testing. Need to fix "except socket.error::" and remove one colon. Also, it told me the listener started on 0.0.0.0:8080 but, it didn't and the listener shows it's listening on whatever IP I originally gave it. Give it a bit more fixup/testing and I'll gladly merge. Let me know if you have any questions. Thanks!

**Comment by rvrsh3ll** [comment]
Looks pretty good. Fix line 151 and remove a colon "except socket.error::". I'll merge then. Thanks!

**Comment by imaibou** [comment]
Sorry for that, I don't know how that slipped in there.
Thanks for the merge.

**Pull request merged**
