### PR TITLE
OS X Mail rule persistance module 

### PR DESCRIPTION
**Pull request by n00py**
Added a new module. The way it works is by creating:
1. applescript stager with some extra code to kill the script monitor upon execution
2. Two plists, one for the new mail rule and one to activate it
3. Drops these files, merges the new plists with the existing mail rules, then deletes the dropped files

When a new email comes in to the victim with the special "trigger" word it will delete the mail and execute the applescript

Reference:
https://github.com/n00py/MailPersist
screen shot 2016-09-10 at 12 53 11 pm

### CODE REVIEW

**Comment by xorrior** [comment]
I'll take a look at this and test during the next few days. Thanks again!

**Comment by xorrior** [comment]
Sorry for the delay on this. Once I'm able to test, I'll merge it with EmPyre and also move it over to the Empire 2.0-beta branch.

**Comment by n00py** [comment]
Thanks! I also have another one I've been working on.  Show I try to put it here or submit it to Empire 2.0 in the future?

**Comment by xorrior** [comment]
Going forward, I would submit any new pull requests to the Empire 2.0 branch. Makes the transition much easier. Thanks again.

**Comment by xorrior** [comment]
I tested this on OSX Sierra and unfortunately couldn't get it to work. 
mail-persistence

Output from terminal after executing the module twice. I also confirmed that the rule was never created. Have you only tested on El Capitan?

**Comment by n00py** [comment]
I tried it on El Capitan on my machine.  

Can you let me know if 
/Users/$user/Library/Mail/V3/MailData

exists on your machine?  Just curious if that directory exists or if it's not V4 or something.

**Comment by xorrior** [comment]
Yep its definitely V4 on my machine. You could probably just add a check for the OSX version and change the path accordingly.

**Comment by n00py** [comment]
You can close this for now, I'll try to add some checks and monkey around with it on Sierra when I get the chance

**Pull request closed without merging**
